site_name: kraken-connector
repo_url: https://github.com/tlg7c5/kraken-connector
site_url: https://tlg7c5.github.io/kraken-connector
site_description: Websockets and HTTP clients for Kraken exchange API
site_author: Terry Garner
edit_uri: edit/main/docs/
repo_name: tlg7c5/kraken-connector
copyright: Maintained by <a href="https://tlg7c5.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          options:
            show_symbol_type_heading: true
            show_submodules: true
            summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            docstring_section_style: list
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tlg7c5/kraken-connector
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/kraken-connector

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
